name: get version
on:
  workflow_dispatch:
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
    - name: Get v tags
      id: get_tag
      run: |
        TAG=$(curl -s \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/tags \
          | jq -r '.[].name | select(startswith("v"))' \
          | head -n 10)
        echo $TAG
        TEMP=$(curl -s \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/tags?per_page=1)
        echo $TEMP
        # echo "tag=$TAG" >> "$GITHUB_OUTPUT"
